name: 'Update with Upstream'
description: 'Update repo with upstream'
author: 'Mark E. Anderson'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-merge'
  color: 'purple'

# Define your inputs here.
inputs:
  repo:
    description: 'Repository Name'
    required: false
  repo-file:
    description: 'Repository List JSON file'
    required: false
  op-token:
    description: '1Password Service Account Token'
    required: true
  branch:
    description: 'Branch to update'
    default: 'main'

runs:
  using: node20
  main: dist/index.js
